version: '3.8'
services:
  go-app:
    container_name: go-app
    build:
      context: ../go-api-insta  
    ports:
      - "3003:3003"  
    links:
      - mongodb-insta  
    depends_on:
      - mongodb-insta  


  mongodb-insta:
    container_name: mongodb-insta
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: insta
      MONGO_INITDB_ROOT_PASSWORD: insta
    ports:
      - "27017:27017"  


  frontend:
    container_name: frontend-insta
    build:
      context: ../spa-insta 
    ports:
      - "3000:3000"  
    depends_on:
      - go-app
